# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: red

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Streamer'
    org_name: 'decodinglove'
    description: 'Decoing our love to machines and humans'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.jpg"
    button:
      enable: true
      text: "Like and subscribe"
      url: "https://youtube.decodinglove.tv"
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} decodingLove'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'


features:
  comment:
    provider: 'giscus'
    giscus:
      repo: 'geoheil/website-decodinglove-comments'
      repo_id: 'R_kgDOMtTwHA'
      category: 'General'
      category_id: 'DIC_kwDOMtTwHM4CiOZa'
